# Generated by Django 3.0.6 on 2020-06-01 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anestesias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anestesia',
            old_name='tipo_cirugiam',
            new_name='tipo_cirugia',
        ),
    ]
