# Generated by Django 2.1.15 on 2020-06-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anestesias', '0002_auto_20200601_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anestesia',
            name='tipo_cirugia',
            field=models.DateField(),
        ),
    ]
